# Generated by Django 4.2.5 on 2023-10-07 16:12

from django.db import migrations, models
import django.db.models.deletion
import employee_of_month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=employee_of_month.models.get_image_upload_path)),
                ('phone', models.CharField(max_length=11)),
                ('job_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeOfTheMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_selected_for_month', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_of_month.employee')),
            ],
        ),
    ]
