# Generated by Django 4.2.5 on 2023-10-03 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_of_the_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='selected_month',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
