# Generated by Django 4.2.5 on 2023-10-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeofthemonth',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_of_month.employee'),
        ),
    ]
