# Generated by Django 4.2.5 on 2023-10-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0002_alter_employeeofthemonth_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
