# Generated by Django 4.2.5 on 2023-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0002_employee_employee_of_the_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_of_the_month',
            new_name='selected',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='selected_month',
        ),
        migrations.AddField(
            model_name='employee',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
