# Generated by Django 4.2.5 on 2023-10-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0003_employee_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeofthemonth',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_of_the_month', to='employee_of_month.employee'),
        ),
    ]
