# Generated by Django 4.2.5 on 2023-10-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0003_rename_employee_of_the_month_employee_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='selected_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
