# Generated by Django 4.2.4 on 2023-10-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0005_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeofthemonth',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='WinnerInteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_of_month.employee')),
                ('current_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_of_month.employeeofthemonth')),
            ],
        ),
    ]
