# Generated by Django 4.2.5 on 2023-10-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0005_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='counter',
            new_name='selection_counter',
        ),
    ]
