# Generated by Django 4.2.4 on 2023-10-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0006_employeeofthemonth_likes_winnerinteractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeofthemonth',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
