# Generated by Django 4.2.4 on 2023-10-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_of_month', '0006_rename_counter_employee_selection_counter'),
        ('employee_of_month', '0007_alter_employeeofthemonth_likes'),
    ]

    operations = [
    ]
